### PR TITLE
[MRG] FIX: bug in lagged updates for L1 regularization

### PR DESCRIPTION
**Pull request by fabianp**
This fixes a bug in the lagged updates of L1 regularization, which was computed wrongly. Added tests.

Another addition of the PR is the inclusion of the flag ```support_lagged``` in the prox. This is needed in order to tell the SAGA algorithm that the prox might not support lagged updates and hence it forces to do "full" updates in each iteration. I need this to be able to use this routine safely on sparse input with other prox functions, such as group lasso or TV.

I also did some renaming/refactoring along the way. The public API should not have changed.

### CODE REVIEW

**Comment by mblondel** [comment]
Does it mean that the pure Python implementation was wrong?

**Comment by fabianp** [comment]
All the opposite. The Cython one was wrong, at least with sparse input and
l1 regularization. The error is subtle, as it only affects the regime in
which the gradient is "big", hence the method seemed to converge but I
realized that it didn't coincide exactly with the Python version . Now both
versions should coincide , look at the extra test I added comparing both
versions with sparse input.

**Comment by fabianp** [comment]
Still not right, I added a failing test for the case of elastic-net penalty

**Comment by fabianp** [comment]
I'm looking into it

**Comment by fabianp** [comment]
It should be fixed now. Caught 2 bugs, one in the computation of w_scale, which becomes exactly zero when eta_alpha = 1, the other one in the computation of the lagged updates in projection_lagged

**Comment by mblondel** [comment]
Looks like the pure Python implementation is proving useful after all :)

I don't really have the mental bandwidth to review this so just tell me when I am good to click on the green button :)

**Comment by fabianp** [comment]
I would say its good. I've been using extensively this code in the last couple of days and I think its stable.

**Comment by mblondel** [comment]
Done. Thanks a lot!

**Pull request merged**
